//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingFactory.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessoriesProduct
    {
        public int IdAccessories { get; set; }
        public int IdProduct { get; set; }
        public string Placement { get; set; }
        public double Width { get; set; }
        public double Lenght { get; set; }
        public int Quantity { get; set; }
    
        public virtual Accessories Accessories { get; set; }
        public virtual Product Product { get; set; }
    }
}
