//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingFactory.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageCloth
    {
        public int Id { get; set; }
        public int IdCloth { get; set; }
        public double Lenght { get; set; }
    
        public virtual Cloth Cloth { get; set; }
    }
}
